"""add vistoria

Revision ID: 3f30cf0aa7a0
Revises: 469c9c8f6a62
Create Date: 2024-10-29 19:36:36.077274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f30cf0aa7a0'
down_revision: Union[str, None] = '469c9c8f6a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vistoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observacao', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_vistoria', sa.Date(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vistoria')
    # ### end Alembic commands ###
