"""add-server-default3

Revision ID: 7bc0dd139679
Revises: 7bbc3d69d3af
Create Date: 2024-11-08 21:02:32.031146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc0dd139679'
down_revision: Union[str, None] = '7bbc3d69d3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conta_usuario', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('fiador', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('inquilino', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('propriedades', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('propriedades', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('inquilino', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('fiador', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('conta_usuario', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###
