"""add unique inspection contract_id

Revision ID: 69cc9460a16c
Revises: 7bc0dd139679
Create Date: 2024-11-13 16:59:29.336606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cc9460a16c'
down_revision: Union[str, None] = '7bc0dd139679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vistoria_contrato_id', 'vistoria', ['contrato_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vistoria_contrato_id', 'vistoria', type_='unique')
    # ### end Alembic commands ###
