"""Add contract, payment, template tables

Revision ID: 0e15d3613bd5
Revises: 8095937401db
Create Date: 2024-10-18 17:41:31.791679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e15d3613bd5'
down_revision: Union[str, None] = '8095937401db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_template', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('garagem', sa.Boolean(), nullable=False),
    sa.Column('garantia', sa.Enum('fiador', 'caução', 'nenhum', name='garantia'), nullable=False),
    sa.Column('animais', sa.Boolean(), nullable=False),
    sa.Column('sublocacao', sa.Boolean(), nullable=False),
    sa.Column('tipo_contrato', sa.Enum('residencial', 'comercial', name='tipo_contrato'), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_calcao', sa.Numeric(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('valor_base', sa.Numeric(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('taxa_reajuste', sa.Enum('IGPM', name='taxa_reajuste'), nullable=True),
    sa.Column('casa_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(), nullable=False),
    sa.Column('fg_pago', sa.Boolean(), nullable=False),
    sa.Column('tipo_pagamento', sa.Enum('dinheiro', 'cartão', 'transferência', 'outro', name='tipo_pagamento'), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('mes_referencia', sa.Enum('janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro', name='mes_referencia'), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelas')
    op.drop_table('contrato')
    op.drop_table('template')
    # ### end Alembic commands ###
