"""add signed field in contract

Revision ID: 88b55110793b
Revises: 3f30cf0aa7a0
Create Date: 2024-10-31 15:40:57.342386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b55110793b'
down_revision: Union[str, None] = '3f30cf0aa7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('pdf_assinado', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrato', 'pdf_assinado')
    # ### end Alembic commands ###
