"""Add unique constraint on cpf and user_id in Tenant

Revision ID: 61adadace3f6
Revises: 97107c4bc232
Create Date: 2024-09-30 16:15:56.479526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61adadace3f6'
down_revision: Union[str, None] = '97107c4bc232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inquilino_cpf', table_name='inquilino')
    op.create_unique_constraint('uq_inquilino_cpf_user_id', 'inquilino', ['cpf', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inquilino_cpf_user_id', 'inquilino', type_='unique')
    op.create_index('ix_inquilino_cpf', 'inquilino', ['cpf'], unique=True)
    # ### end Alembic commands ###
