"""alter assinatura_hash in conta_usuario string > Text

Revision ID: 7bbc3d69d3af
Revises: cae2d820da65
Create Date: 2024-11-08 14:08:24.458011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbc3d69d3af'
down_revision: Union[str, None] = 'cae2d820da65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conta_usuario', 'assinatura_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('conta_usuario', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conta_usuario', 'cep',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('conta_usuario', 'assinatura_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
