"""add foto in houses

Revision ID: 976ebe57063d
Revises: cd25c31e85eb
Create Date: 2024-09-23 21:03:31.479089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976ebe57063d'
down_revision: Union[str, None] = 'cd25c31e85eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casas', sa.Column('foto', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casas', 'foto')
    # ### end Alembic commands ###
