"""add foto in user

Revision ID: 87b226a9f724
Revises: 976ebe57063d
Create Date: 2024-09-23 21:05:22.476726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b226a9f724'
down_revision: Union[str, None] = '976ebe57063d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta_usuario', sa.Column('foto', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_usuario', 'foto')
    # ### end Alembic commands ###
