name: Python Test with Database Migration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECURITY__JWT_SECRET_KEY: very-not-secret
      DATABASE__HOSTNAME: localhost
      DATABASE__PORT: 5432
      DATABASE__DB: my_test_db
      DATABASE__USERNAME: postgres
      DATABASE__PASSWORD: postgres
      DATABASE_URL: postgresql://postgres:postgres@localhost/my_test_db
      SECURITY__EMAIL_HOST: ${{ secrets.SECURITY__EMAIL_HOST }}
      SECURITY__SERVICE_ACCOUNT: ${{ secrets.SECURITY__SERVICE_ACCOUNT }}
      SECURITY__SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.SECURITY__SERVICE_ACCOUNT_PROJECT_ID }}
      SECURITY__SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.SECURITY__SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
      SECURITY__SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SECURITY__SERVICE_ACCOUNT_PRIVATE_KEY }}
      SECURITY__SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SECURITY__SERVICE_ACCOUNT_CLIENT_EMAIL }}
      SECURITY__SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.SECURITY__SERVICE_ACCOUNT_CLIENT_ID }}
      SECURITY__CLIENT_X509_CERT_URL: ${{ secrets.SECURITY__CLIENT_X509_CERT_URL }}
      SECURITY__AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs

    services:
      postgres_db:
        image: postgres:16
        env:
          POSTGRES_DB: my_test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply Database Migrations
      run: |
        alembic upgrade head

    - name: Run MyPy
      run: |
        mypy .

    - name: Run tests
      run: |
        pytest